services:
  user-service:
    image: ginhenrick/user-service:latest
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    depends_on:
      - database

  product-service:
    image: ginhenrick/product-service:latest
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    depends_on:
      - database
      - cache

  order-service:
    image: ginhenrick/order-service:latest
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    depends_on:
      - database
      - notification-service

  payment-service:
    image: ginhenrick/payment-service:latest
    ports:
      - "5004:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    depends_on:
      - order-service

  notification-service:
    image: ginhenrick/notification-service:latest
    ports:
      - "5005:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging

  api-gateway:
    image: ginhenrick/api-gateway:latest
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service
      - notification-service

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=191003
    ports:
      # - "1433:1433"
      - "1434:1433"  # Đổi cổng bên ngoài thành 1434 để tránh xung đột với sqlserver

  cache:
    image: redis:latest
    ports:
      # - "6379:6379"
      - "6380:6379"  # Đổi cổng bên ngoài thành 6380 để tránh xung đột với redis_container
