name: CI/CD for E-commerce Microservices

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Sử dụng self-hosted runner đã cài trên server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker images for each service
      - name: Build and push Docker images for UserService
        uses: docker/build-push-action@v2
        with:
          context: ./services/UserService
          tags: tuongnguyen191003/user-service:latest
          push: true

      - name: Build and push Docker images for ProductService
        uses: docker/build-push-action@v2
        with:
          context: ./services/ProductService
          tags: tuongnguyen191003/product-service:latest
          push: true

      - name: Build and push Docker images for OrderService
        uses: docker/build-push-action@v2
        with:
          context: ./services/OrderService
          tags: tuongnguyen191003/order-service:latest
          push: true

      - name: Build and push Docker images for PaymentService
        uses: docker/build-push-action@v2
        with:
          context: ./services/PaymentService
          tags: tuongnguyen191003/payment-service:latest
          push: true

      - name: Build and push Docker images for NotificationService
        uses: docker/build-push-action@v2
        with:
          context: ./services/NotificationService
          tags: tuongnguyen191003/notification-service:latest
          push: true

  deploy:
    runs-on: self-hosted  # Sử dụng self-hosted runner trên server để tránh SSH qua internet
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Staging Environment
        run: |
          cd /home/tuongnguyen/Desktop/ecommerce-microservices/ecommerce-microservices
          docker-compose -f docker-compose.staging.yml pull
          docker-compose -f docker-compose.staging.yml up -d
